name: Build MoguPet macOS App
on:
  workflow_dispatch: #支持手动启动打包
  push:
    branches: [main]

jobs:
  build-mac:
    runs-on: macos-latest
    env:
      MACOSX_DEPLOYMENT_TARGET: "11.0"
    steps:
      - name: 拉取代码
        uses: actions/checkout@v5

      - name: 配置Python3.11
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install PyQt6 pyinstaller

      - name: PyInstaller打包生成Mac APP
        run: |
          pyinstaller \
            --windowed \
            --noconfirm \
            --clean \
            --name "MoguPet" \
            --add-data "mogu.png:." \
            mogu_pet.py

      - name: 压缩APP为zip包
        run: ditto -c -k --keepParent dist/MoguPet.app dist/MoguPet_Mac.zip

      - name: 上传成品文件
        uses: actions/upload-artifact@v4
        with:
          name: MoguPet-Mac成品
          path: dist/MoguPet_Mac.zip
